# Generated by Django 3.1.7 on 2021-03-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Update', models.DateTimeField(auto_now_add=True)),
                ('Opened', models.BooleanField(blank=True, default=False)),
                ('Select', models.BooleanField(blank=True, default=False)),
                ('Focus', models.BooleanField(blank=True, default=False)),
                ('Group', models.IntegerField(blank=True, default=0)),
                ('fileID', models.CharField(blank=True, max_length=150, null=True)),
                ('OriginalFileName', models.CharField(blank=True, max_length=500, null=True)),
                ('FileName', models.CharField(blank=True, max_length=150, null=True)),
                ('PatientID', models.IntegerField(blank=True, null=True)),
                ('PatientName', models.CharField(blank=True, max_length=150, null=True)),
                ('Age', models.IntegerField(blank=True, default=0, null=True)),
                ('Sex', models.CharField(blank=True, max_length=3, null=True)),
                ('Tracer', models.CharField(blank=True, max_length=150, null=True)),
                ('SUVR', models.FloatField(blank=True, default=None, null=True)),
                ('Centiloid', models.FloatField(blank=True, default=None, null=True)),
                ('Composite', models.FloatField(blank=True, null=True)),
                ('Frontal_L', models.FloatField(blank=True, null=True)),
                ('Frontal_R', models.FloatField(blank=True, null=True)),
                ('Parietal_L', models.FloatField(blank=True, null=True)),
                ('Parietal_R', models.FloatField(blank=True, null=True)),
                ('Temporal_L', models.FloatField(blank=True, null=True)),
                ('Temporal_R', models.FloatField(blank=True, null=True)),
                ('Cingulate_L', models.FloatField(blank=True, null=True)),
                ('Cingulate_R', models.FloatField(blank=True, null=True)),
                ('Striatum_L', models.FloatField(blank=True, null=True)),
                ('Striatum_R', models.FloatField(blank=True, null=True)),
                ('Occipital_L', models.FloatField(blank=True, null=True)),
                ('Occipital_R', models.FloatField(blank=True, null=True)),
                ('Thalamus_L', models.FloatField(blank=True, null=True)),
                ('Thalamus_R', models.FloatField(blank=True, null=True)),
                ('Frontal_L_C', models.FloatField(blank=True, null=True)),
                ('Frontal_R_C', models.FloatField(blank=True, null=True)),
                ('Cingulate_L_C', models.FloatField(blank=True, null=True)),
                ('Cingulate_R_C', models.FloatField(blank=True, null=True)),
                ('Striatum_L_C', models.FloatField(blank=True, null=True)),
                ('Striatum_R_C', models.FloatField(blank=True, null=True)),
                ('Thalamus_L_C', models.FloatField(blank=True, null=True)),
                ('Thalamus_R_C', models.FloatField(blank=True, null=True)),
                ('Occipital_L_C', models.FloatField(blank=True, null=True)),
                ('Occipital_R_C', models.FloatField(blank=True, null=True)),
                ('Parietal_L_C', models.FloatField(blank=True, null=True)),
                ('Parietal_R_C', models.FloatField(blank=True, null=True)),
                ('Temporal_L_C', models.FloatField(blank=True, null=True)),
                ('Temporal_R_C', models.FloatField(blank=True, null=True)),
                ('Composite_C', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-Update'],
            },
        ),
    ]
