# Generated by Django 3.1.7 on 2021-03-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='Cingulate_L',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Cingulate_L_C',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Cingulate_R',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Cingulate_R_C',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Composite',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Composite_C',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Frontal_L',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Frontal_L_C',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Frontal_R',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Frontal_R_C',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Occipital_L',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Occipital_L_C',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Occipital_R',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Occipital_R_C',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Parietal_L',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Parietal_L_C',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Parietal_R',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Parietal_R_C',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Striatum_L',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Striatum_L_C',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Striatum_R',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Striatum_R_C',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Temporal_L',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Temporal_L_C',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Temporal_R',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Temporal_R_C',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Thalamus_L',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Thalamus_L_C',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Thalamus_R',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Thalamus_R_C',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='fileID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
