# Generated by Django 3.1.7 on 2021-04-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20210428_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='ScanDate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
