# Generated by Django 3.1.7 on 2021-05-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20210510_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='slice',
            name='InvB64Data',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
