# Generated by Django 3.1.7 on 2021-05-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_slice_invb64data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slice',
            name='InvB64Data',
        ),
    ]
