# Generated by Django 3.1.7 on 2021-05-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_remove_slice_invb64data'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='Complete',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
