# Generated by Django 3.1.7 on 2021-04-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_auto_20210428_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='AcquisitionDateTime',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
