# Generated by Django 3.1.7 on 2021-04-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_auto_20210429_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='PatientID',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
