# Generated by Django 3.1.7 on 2021-05-27 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_auto_20210527_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='SUVR',
            new_name='Global',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='SUVR_C',
            new_name='Global_C',
        ),
    ]
