# Generated by Django 3.1.7 on 2021-04-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_auto_20210429_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='InputAffineParamsX0',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='InputAffineParamsX1',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='InputAffineParamsX2',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='InputAffineParamsX3',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='InputAffineParamsY0',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='InputAffineParamsY1',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='InputAffineParamsY2',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='InputAffineParamsY3',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='InputAffineParamsZ0',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='InputAffineParamsZ1',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='InputAffineParamsZ2',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='InputAffineParamsZ3',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='OutputAffineParamsX0',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='OutputAffineParamsX1',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='OutputAffineParamsX2',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='OutputAffineParamsX3',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='OutputAffineParamsY0',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='OutputAffineParamsY1',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='OutputAffineParamsY2',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='OutputAffineParamsY3',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='OutputAffineParamsZ0',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='OutputAffineParamsZ1',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='OutputAffineParamsZ2',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='OutputAffineParamsZ3',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
