# Generated by Django 3.1.7 on 2021-04-29 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_auto_20210429_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='InputAffineParamsX1',
        ),
        migrations.RemoveField(
            model_name='case',
            name='InputAffineParamsX2',
        ),
        migrations.RemoveField(
            model_name='case',
            name='InputAffineParamsX3',
        ),
        migrations.RemoveField(
            model_name='case',
            name='InputAffineParamsY0',
        ),
        migrations.RemoveField(
            model_name='case',
            name='InputAffineParamsY2',
        ),
        migrations.RemoveField(
            model_name='case',
            name='InputAffineParamsY3',
        ),
        migrations.RemoveField(
            model_name='case',
            name='InputAffineParamsZ0',
        ),
        migrations.RemoveField(
            model_name='case',
            name='InputAffineParamsZ1',
        ),
        migrations.RemoveField(
            model_name='case',
            name='InputAffineParamsZ3',
        ),
        migrations.RemoveField(
            model_name='case',
            name='OutputAffineParamsX1',
        ),
        migrations.RemoveField(
            model_name='case',
            name='OutputAffineParamsX2',
        ),
        migrations.RemoveField(
            model_name='case',
            name='OutputAffineParamsX3',
        ),
        migrations.RemoveField(
            model_name='case',
            name='OutputAffineParamsY0',
        ),
        migrations.RemoveField(
            model_name='case',
            name='OutputAffineParamsY2',
        ),
        migrations.RemoveField(
            model_name='case',
            name='OutputAffineParamsY3',
        ),
        migrations.RemoveField(
            model_name='case',
            name='OutputAffineParamsZ0',
        ),
        migrations.RemoveField(
            model_name='case',
            name='OutputAffineParamsZ1',
        ),
        migrations.RemoveField(
            model_name='case',
            name='OutputAffineParamsZ3',
        ),
    ]
